### ISSUE TITLE
Chevron Location is non Canon if camouflage is used

### ISSUE THREAD

**Issue by SunnyM00n** [StargateMC/IssueTracker#129]
So, it's annoying me a while now that the chevrons move when you camouflage the Stargate Base. I dug throgh the config while i was bored and found the option “variableChevronPositions”, i deactivated that and noticed that the chevrons don't move anymore when you camouflage the Base. I ask for deactivating this config part because this would make the stargates more Canon (and the ones that would be hidden are the Galaxy Selection Chevrons, so it would make more sense.)

**Comment by DEVensiv** [comment]
In addition to that i just want to mention that even if you dial a address with 7 or 8 chevrons all 9 will be selected and activated even tho that should not be the case.

**Comment by Joey4213** [comment]
thats only because of the current dialing logic, the reason behind it is because bysokar currently has it so 9 chevrons is required for a galaxy dial and 7 is within system with 8 being inert

**Comment by StargateMC** [comment]
Camouflage operates similarly to what the SGC gate does in the show, meaning the bottom 2 chevrons are hidden.

You're right, they should in theory not be activated for a 7 chevron dial but due to the way SGCraft works this isn't done presently - its random instead.

This isnt a priority, but would be nice to be tweaked.
