### ISSUE TITLE
Add a suicide command to allow players to get 'unstuck'

### ISSUE THREAD

**Issue by FoosterKing** [StargateMC/IssueTracker#166]
I'm in a predicament where I cannot use a stargate, build a ship to get off a planet or use a pre-existing ship. This is why I think a command should be added where you can be teleported back to the SGC. Not only should this command respawn you, but delete all items that you currently have on you.(This way it can't be used to exploit) This would also reduce the amount of times admins have to directly help players out.

**Comment by StargateMC** [comment]
So you mean you want a suicide command.
Sure thing!

**Comment by JayCoolGuy** [comment]
Would this suicide command take you back to the SGC as fooster wanted? Because if not, there's no real point to it, you can suicide yourself by falling from a high place for example and still respawn on the same planet.  And if it does take you back to the SGC, i think it takes away from the whole idea of being "stranded" on a planet and having to find your way out yourself.

**Comment by StargateMC** [comment]
@JayCoolGuy then why cant you make a gate on a world? or a ship?

**Comment by JayCoolGuy** [comment]
Well I suppose, if there is somehow a planet you are trapped on with not enough resources to make either than you are kind of fucked in that situation although the only types of planets that could possibly be like that are destinations that are most likely considered unsafe (moon, etc) so if you died you would respawn in the SGC anyway.

**Comment by Joey4213** [comment]
Done
