### ISSUE TITLE
AE2 Autocrafting “Bug” with Industrial Craft items

### ISSUE THREAD

**Issue by JayCoolGuy** [StargateMC/IssueTracker#175]
This could be that I’m doing something wrong (most likely) so far most of the industrial craft items I’ve tried to auto craft have been experiencing the same “bug” where the items required for the craft are created but the finished product is left scheduled and never completed.

**Comment by nosknut** [comment]
Adding to this issue with some updated information:
The issue is likely with energy metadata. Some recipees using crystals are incapable of being crafted by CRAFTING patterns but not by PRODUCTION patterns. The required items do exist in the system and are detected so i think the issue is with properly injecting the crafting pattern from the interface to the molecular assembler. If one adds a crafting pattern into an assembler manually and supply the assembler with the items, it will craft properly. I have created a temporary workaround by manually and permanently adding a version of the pattern for crafting directly in the molecular assembler, and a single production pattern for the same recipee in the ajacent interface. This will cause the me system to view the assembler as a machine instead of a crafting system and directly export the items to the preprogrammed assembler while ignoring the weird metadata.
