### ISSUE TITLE
Suggestion - Adding Ender IO

### ISSUE THREAD

**Issue by SunnyM00n** [StargateMC/IssueTracker#260]
## What is your suggestion?
> I suggest forking the Ender IO mod on github and removing all teleportation functionality from it to be able to include it into the mod pack 

>Why is this important?
> Ender IO includes many quality of life functionality that is useful for constructing and decorating 

## How will this benefit players?
> Players will be able to choose the item transportation method they are familiar with. They will be able to create their bases how they want

>Why is this important?
>This would add a major quality of life increase

## How will this change for players?
> Shouldn’t cause any issues

>Why is this important?
>Players can choose more freely what machines and mods they want to use

## Do you consider this suggestion a:

- [ ] Must (Important to keep players happy)
- [x] Should (Beneficial to players, but can do without)
- [ ] Could (Beneficial to players, there is no important reason to do it

**Comment by draksterau** [comment]
What is 1 thing this mod adds that others do not?

**Comment by mainesi** [comment]
The ability to use one block for multiple pipe types

**Comment by BenFRC5147** [comment]
I second, the teleportation is limited to a few blocks and the Conduit functionality alone is so nice that I'd want it just for that, add on the ability to paint blocks to look like other blocks, the built in way to seal walls with conduit facades, and more variety of machines is also quite nice. Also, Conduits have significantly less impact on performance than Mekanism pipes do since they have no animation, so people with performance issues may prefer to use those

**Comment by Joey4213** [comment]
I third this, I can also limit all the aspects of cross-dim "anything"

**Comment by Joey4213** [comment]
@draksterau says this is a definite NO
